### ISSUE TITLE
ImportError: No module named woocommerce

### ISSUE THREAD

**Issue by ericmachine88** [techreceptives/connector-woocommerce#1]
Hi there,

Need your help. Can't install your module.

2015-09-14 10:56:58,619 3128 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-09-14 10:57:11,809 3128 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-09-14 10:57:12,619 3128 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2015-09-14 10:57:13,058 3128 INFO ? werkzeug: 10.3.8.210 - - [14/Sep/2015 10:57:13] "GET / HTTP/1.1" 500 -
2015-09-14 10:57:13,066 3128 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/home/odoo/odoo-dev/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 1289, in __call__
    self.load_addons()
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 1308, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/__init__.py", line 22, in <module>
    from . import model
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/model/__init__.py", line 22, in <module>
    from . import backend
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/model/backend.py", line 23, in <module>
    from woocommerce import API
ImportError: No module named woocommerce

Any help? Thanks.

**Comment by ericmachine88** [comment]
I just realised I need to install this
pip install woocommerce

But now I got a new error

2015-09-14 11:22:57,504 3012 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/home/odoo/odoo-dev/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 1289, in __call__
    self.load_addons()
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 1308, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/__init__.py", line 22, in <module>
    from . import model
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/model/__init__.py", line 22, in <module>
    from . import backend
  File "/home/odoo/odoo-dev/woocommerce/connector_woocommerce/model/backend.py", line 25, in <module>
    from openerp.addons.connector.session import ConnectorSession
  File "/home/odoo/odoo-dev/odoo/openerp/modules/module.py", line 79, in load_module
    f, path, descr = imp.find_module(module_part, ad_paths)
ImportError: No module named connector

any idea?

**Comment by DeepikaBhojani** [comment]
you need to install modules named connector, connector-ecommerce, e-commerce and sale-workflow. These modules are used as dependency in connector-woocommerce. You can get these modules from OCA community.

Here are the links:
https://github.com/OCA/connector
https://github.com/OCA/connector-ecommerce
https://github.com/OCA/sale-workflow
https://github.com/OCA/e-commerce

**Comment by ericmachine88** [comment]
Thanks mate, you are right. Got it installed :)

I followed your video here
https://www.youtube.com/watch?t=91&v=vz759wsZFak

Now the next issue is I can't import products (only managed to import category). 

Check the screenshots
http://imgur.com/a/olsfa

Any idea? Thanks.

**Comment by DeepikaBhojani** [comment]
Update the Connector Woo Odoo plugin in Woo Commerce to version 2.4.6 and it will work.

**Comment by ericmachine88** [comment]
Nice, it works :)
