### ISSUE TITLE
KeyError: 'product_category'

### ISSUE THREAD

**Issue by mcassuto** [techreceptives/connector-woocommerce#3]
The backend is configured and I have a test successful msg when I test the connection.
When I  run a job to import the product categories, I receive the following error:

Traceback (most recent call last):
  File "/home/mc/odoo/git/connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/home/mc/odoo/git/connector/connector/queue/job.py", line 467, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/home/mcl/odoo/git/connector-woocommerce/woocommerceerpconnect/unit/import_synchronizer.py", line 285, in import_record
    importer.run(woo_id, force=force)
  File "/home/mcodoo/git/connector-woocommerce/woocommerceerpconnect/unit/import_synchronizer.py", line 203, in run
    self._import_dependencies()
  File "/home/mc/odoo/git/connector-woocommerce/woocommerceerpconnect/model/product_category.py", line 142, in _import_dependencies
    record = record['product_category']
KeyError: 'product_category'

**Comment by parthivgls** [comment]
can you check that you have set "permlinks" to /product and following clean url concept in your wordpress installation, as woocomerce API heavily rely on clean url.

**Comment by parthivgls** [comment]
issue is now fixed.

**Comment by mcassuto** [comment]
@parthivgls sorry I did not have time to check this before
please explain why the permlinkds configure should fix this ? 
Woo has a wonderful API cery well documented... Are you using it ?

**Comment by mcassuto** [comment]
I did not confirm...
